version: "3.8"

services:
  database:
    container_name: "apps7_database"
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./database:/docker-entrypoint-initdb.d
